// <auto-generated />
using System;
using LMCM_BE.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMCM_BE.Migrations
{
    [DbContext(typeof(LMCM_DBContext))]
    [Migration("20250331043057_V7")]
    partial class V7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMCM_BE.Models.AcceptanceRecord", b =>
                {
                    b.Property<Guid>("AcceptanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Acceptance_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Acceptance_Date");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Author_ID");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contract_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Final_Price");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AcceptanceId")
                        .HasName("PK__Acceptan__FC008882C329FB76");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ContractId");

                    b.ToTable("Acceptance_Record", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.BudgetProposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Proposal_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Author_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("ProposalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Proposal_Date");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProposalId")
                        .HasName("PK__Budget_P__C9D0461F9553543D");

                    b.HasIndex("AuthorId");

                    b.ToTable("Budget_Proposals", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Clo", b =>
                {
                    b.Property<Guid>("CloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CLO_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CloDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLO_Description");

                    b.Property<string>("CloName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO_Name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("CloId")
                        .HasName("PK__CLO__C3755EADCB5474B3");

                    b.HasIndex("SyllabusId");

                    b.ToTable("CLO", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.ConstructivistQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Question_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("QuestionDetail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Question_Detail");

                    b.Property<string>("QuestionName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_Name");

                    b.Property<int>("SessionNo")
                        .HasColumnType("int")
                        .HasColumnName("Session_No");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("QuestionId")
                        .HasName("PK__Construc__B0B2E4C62C9AF47D");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Constructivist_Question", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contract_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Author_ID");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Contract_Date");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Contract_Value");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contractor_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Proposal_ID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ContractId")
                        .HasName("PK__Contract__5E2E73DA08AE6527");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ContractorId");

                    b.HasIndex("ProposalId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("LMCM_BE.Models.ContractValueItem", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Value_ID");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Contract_Value");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Measurement_Unit");

                    b.Property<string>("QualityRequirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Quality_Requirements");

                    b.Property<decimal>("StandardRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Standard_Rate");

                    b.Property<decimal>("ValueRatioForUpdate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value_Ratio_For_Update");

                    b.HasKey("ValueId")
                        .HasName("PK__ContractValueItem");

                    b.ToTable("Contract_Value_Item", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Contractor", b =>
                {
                    b.Property<Guid>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contractor_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Bank_Account_Number");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Bank_Name");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contractor_Name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Employee_Code");

                    b.Property<string>("IdCardNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ID_Card_Number");

                    b.Property<string>("IdIssuedPlace")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ID_Issued_Place");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Phone_Number");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Tax_Code");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ContractorId")
                        .HasName("PK__Contract__61C4678D31963763");

                    b.ToTable("Contractor", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Curriculum", b =>
                {
                    b.Property<Guid>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Curriculum_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Approved_Date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Code");

                    b.Property<string>("CurriculumDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Curriculum_Description");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Name");

                    b.Property<string>("CurriculumNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Name_English");

                    b.Property<string>("DecisionNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Decision_No");

                    b.Property<string>("EnglishVocationalName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("English_Vocational_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("VocationalCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Vocational_Code");

                    b.Property<string>("VocationalName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Vocational_Name");

                    b.HasKey("CurriculumId")
                        .HasName("PK__Curricul__2F88E2C215B9DA93");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("LMCM_BE.Models.CurriculumsSubject", b =>
                {
                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Curriculum_ID");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("Credit")
                        .HasColumnType("int");

                    b.Property<int?>("Options")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TermNo")
                        .HasColumnType("int")
                        .HasColumnName("Term_No");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("CurriculumId", "SubjectId", "CreatedAt")
                        .HasName("PK__Curricul__39754AB27565F259");

                    b.HasIndex("SubjectId");

                    b.ToTable("Curriculums_Subjects", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.DocumentTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Template_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Author_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Template_Name");

                    b.Property<string>("TemplateType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Template_Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TemplateId")
                        .HasName("PK__Document__E7FB8F01453EB5C0");

                    b.HasIndex("AuthorId");

                    b.ToTable("Document_Templates", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.GradingStructure", b =>
                {
                    b.Property<Guid>("StructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Structure_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AssessmentComponent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Assessment_Component");

                    b.Property<string>("AssessmentType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Assessment_Type");

                    b.Property<string>("Clo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("How")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Min_Value");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Part")
                        .HasColumnType("int");

                    b.Property<string>("QuestionNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_No");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_Type");

                    b.Property<string>("Reference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SessionNo")
                        .HasColumnType("int")
                        .HasColumnName("Session_No");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StructureNo")
                        .HasColumnType("int")
                        .HasColumnName("Structure_No");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(19, 2)");

                    b.HasKey("StructureId")
                        .HasName("PK__Grading___71D721C6418A3D83");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Grading_Structure", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterial", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Material_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsImportedMaterial")
                        .HasColumnType("bit")
                        .HasColumnName("is_Imported_Material");

                    b.Property<bool?>("IsMainMaterial")
                        .HasColumnType("bit")
                        .HasColumnName("is_Main_Material");

                    b.Property<string>("LearningType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("MaterialDetailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Material_Detail_ID");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Material_Name");

                    b.Property<int?>("MaterialNo")
                        .HasColumnType("int")
                        .HasColumnName("Material_No");

                    b.Property<string>("MaterialQuantity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Material_Quantity");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Learning__3A09B0FDDC2985A2");

                    b.HasIndex("MaterialDetailId");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Learning_Materials", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterialChangesHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("History_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Change_Description");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Change_Type");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Completion_Date");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contract_ID");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Code");

                    b.Property<string>("LearningMaterialType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Learning_Material_Type");

                    b.Property<string>("StartTerm")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Start_Term");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User_ID");

                    b.HasKey("HistoryId")
                        .HasName("PK__Learning__A6BABA375282CF16");

                    b.HasIndex("ContractId");

                    b.HasIndex("SyllabusId");

                    b.HasIndex("UserId");

                    b.ToTable("Learning_Material_Changes_History", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterialDetail", b =>
                {
                    b.Property<Guid>("MaterialDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Material_Detail_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Edition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ISBN");

                    b.Property<string>("MaterialDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Material_Description");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Material_Name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Published_Date");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaterialDetailId")
                        .HasName("PK__Learning__700CBEE1C557F788");

                    b.ToTable("Learning_Material_Detail", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Notification_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User_ID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__8C1160B5E7DB044A");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Plo", b =>
                {
                    b.Property<Guid>("PloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PLO_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Curriculum_ID");

                    b.Property<string>("PloDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PLO_Description");

                    b.Property<string>("PloName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PLO_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("PloId")
                        .HasName("PK__PLO__3BEF007EF96FBDCC");

                    b.HasIndex("CurriculumId");

                    b.ToTable("PLO", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.PloSubject", b =>
                {
                    b.Property<Guid>("PloId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PLO_ID");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("PloId", "SubjectId", "CreatedAt")
                        .HasName("PK__PLO_Subj__2D12A80ECEB98055");

                    b.HasIndex("SubjectId");

                    b.ToTable("PLO_Subjects", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Schedule_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Clos")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Itu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ITU");

                    b.Property<string>("LecturerMaterial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lecturer_Material");

                    b.Property<string>("LecturerMaterialUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lecturer_Material_Url");

                    b.Property<string>("LecturerTask")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lecturer_Task");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleNo")
                        .HasColumnType("int")
                        .HasColumnName("Schedule_No");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentMaterial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Student_Material");

                    b.Property<string>("StudentMaterialUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Student_Material_Url");

                    b.Property<string>("StudentTask")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Student_Task");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__8C4D3BBBEF8E0EE6");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool?>("IsConstructivist")
                        .HasColumnType("bit")
                        .HasColumnName("isConstructivist");

                    b.Property<string>("Method")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Reality")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject_Code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject_Name");

                    b.Property<string>("SubjectNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject_Name_English");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__D98F54D69CFFB5AE");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LMCM_BE.Models.Syllabus", b =>
                {
                    b.Property<Guid>("SyllabusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Approved_Date");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Name");

                    b.Property<string>("CourseNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Name_English");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DecisionNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Decision_No");

                    b.Property<string>("DegreeLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Degree_Level");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearningTeachingMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Learning_Teaching_Method");

                    b.Property<decimal?>("MinGpaToPass")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Min_GPA_to_Pass");

                    b.Property<int?>("NoOfCredits")
                        .HasColumnType("int")
                        .HasColumnName("No_of_Credits");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreRequisite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pre_requisite");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Previous_Version_ID");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Program_Name");

                    b.Property<decimal?>("ScoringScale")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Scoring_Scale");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentTask")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Student_Task");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID");

                    b.Property<string>("TimeAllocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Time_Allocation");

                    b.Property<string>("Tools")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("SyllabusId")
                        .HasName("PK__Syllabus__2F9B49501A14500F");

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Syllabus", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.AcceptanceRecord", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Author")
                        .WithMany("AcceptanceRecords")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Acceptanc__Autho__19DFD96B");

                    b.HasOne("LMCM_BE.Models.Contract", "Contract")
                        .WithMany("AcceptanceRecords")
                        .HasForeignKey("ContractId")
                        .IsRequired()
                        .HasConstraintName("FK__Acceptanc__Contr__1AD3FDA4");

                    b.Navigation("Author");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("LMCM_BE.Models.BudgetProposal", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Author")
                        .WithMany("BudgetProposals")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Budget_Pr__Autho__0C85DE4D");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LMCM_BE.Models.Clo", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("Clos")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__CLO__Syllabus_ID__7D439ABD");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.ConstructivistQuestion", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("ConstructivistQuestions")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Construct__Sylla__778AC167");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.Contract", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Author")
                        .WithMany("Contracts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Autho__1332DBDC");

                    b.HasOne("LMCM_BE.Models.Contractor", "Contractor")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractorId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Contr__14270015");

                    b.HasOne("LMCM_BE.Models.BudgetProposal", "Proposal")
                        .WithMany("Contracts")
                        .HasForeignKey("ProposalId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Propo__123EB7A3");

                    b.Navigation("Author");

                    b.Navigation("Contractor");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("LMCM_BE.Models.CurriculumsSubject", b =>
                {
                    b.HasOne("LMCM_BE.Models.Curriculum", "Curriculum")
                        .WithMany("CurriculumsSubjects")
                        .HasForeignKey("CurriculumId")
                        .IsRequired()
                        .HasConstraintName("FK__Curriculu__Curri__46E78A0C");

                    b.HasOne("LMCM_BE.Models.Subject", "Subject")
                        .WithMany("CurriculumsSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Curriculu__Subje__47DBAE45");

                    b.Navigation("Curriculum");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LMCM_BE.Models.DocumentTemplate", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Author")
                        .WithMany("DocumentTemplates")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Document___Updat__208CD6FA");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LMCM_BE.Models.GradingStructure", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("GradingStructures")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Grading_S__Sylla__71D1E811");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterial", b =>
                {
                    b.HasOne("LMCM_BE.Models.LearningMaterialDetail", "MaterialDetail")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("MaterialDetailId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Learning___Mater__66603565");

                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Learning___Sylla__656C112C");

                    b.Navigation("MaterialDetail");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterialChangesHistory", b =>
                {
                    b.HasOne("LMCM_BE.Models.Contract", "Contract")
                        .WithMany("LearningMaterialChangesHistories")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK__Learning___Contr__25518C17");

                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany()
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LearningMaterialChangesHistory_Syllabus");

                    b.HasOne("LMCM_BE.Models.User", "User")
                        .WithMany("LearningMaterialChangesHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Learning___User___245D67DE");

                    b.Navigation("Contract");

                    b.Navigation("Syllabus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMCM_BE.Models.Notification", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__User___02084FDA");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMCM_BE.Models.Plo", b =>
                {
                    b.HasOne("LMCM_BE.Models.Curriculum", "Curriculum")
                        .WithMany("Plos")
                        .HasForeignKey("CurriculumId")
                        .IsRequired()
                        .HasConstraintName("FK__PLO__Curriculum___4D94879B");

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("LMCM_BE.Models.PloSubject", b =>
                {
                    b.HasOne("LMCM_BE.Models.Plo", "Plo")
                        .WithMany("PloSubjects")
                        .HasForeignKey("PloId")
                        .IsRequired()
                        .HasConstraintName("FK__PLO_Subje__PLO_I__52593CB8");

                    b.HasOne("LMCM_BE.Models.Subject", "Subject")
                        .WithMany("PloSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__PLO_Subje__Subje__534D60F1");

                    b.Navigation("Plo");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LMCM_BE.Models.Schedule", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("Schedules")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Schedule__Syllab__6C190EBB");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.Syllabus", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "PreviousVersion")
                        .WithMany("InversePreviousVersion")
                        .HasForeignKey("PreviousVersionId")
                        .HasConstraintName("FK__Syllabus__Previo__5AEE82B9");

                    b.HasOne("LMCM_BE.Models.Subject", "Subject")
                        .WithMany("Syllabus")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Syllabus__Subjec__59FA5E80");

                    b.Navigation("PreviousVersion");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMCM_BE.Models.BudgetProposal", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("LMCM_BE.Models.Contract", b =>
                {
                    b.Navigation("AcceptanceRecords");

                    b.Navigation("LearningMaterialChangesHistories");
                });

            modelBuilder.Entity("LMCM_BE.Models.Contractor", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("LMCM_BE.Models.Curriculum", b =>
                {
                    b.Navigation("CurriculumsSubjects");

                    b.Navigation("Plos");
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterialDetail", b =>
                {
                    b.Navigation("LearningMaterials");
                });

            modelBuilder.Entity("LMCM_BE.Models.Plo", b =>
                {
                    b.Navigation("PloSubjects");
                });

            modelBuilder.Entity("LMCM_BE.Models.Subject", b =>
                {
                    b.Navigation("CurriculumsSubjects");

                    b.Navigation("PloSubjects");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.Syllabus", b =>
                {
                    b.Navigation("Clos");

                    b.Navigation("ConstructivistQuestions");

                    b.Navigation("GradingStructures");

                    b.Navigation("InversePreviousVersion");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("LMCM_BE.Models.User", b =>
                {
                    b.Navigation("AcceptanceRecords");

                    b.Navigation("BudgetProposals");

                    b.Navigation("Contracts");

                    b.Navigation("DocumentTemplates");

                    b.Navigation("LearningMaterialChangesHistories");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
