// <auto-generated />
using System;
using BusinessObject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMCM_BE.Migrations
{
    [DbContext(typeof(LMCM_DBContext))]
    partial class LMCM_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMCM_BE.Models.AcceptanceRecord", b =>
                {
                    b.Property<Guid>("AcceptanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Acceptance_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Acceptance_Date");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contract_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Final_Price");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AcceptanceId")
                        .HasName("PK__Acceptan__FC008882EB6B5A19");

                    b.HasIndex("ContractId");

                    b.ToTable("Acceptance_Record", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.BudgetProposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Proposal_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Author_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("ProposalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Proposal_Date");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProposalId")
                        .HasName("PK__Budget_P__C9D0461F9781A89B");

                    b.HasIndex("AuthorId");

                    b.ToTable("Budget_Proposals", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Clo", b =>
                {
                    b.Property<Guid>("CloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CLO_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CloDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO_Description");

                    b.Property<string>("CloName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO_Name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CloId")
                        .HasName("PK__CLO__C3755EAD5A32F777");

                    b.HasIndex("SyllabusId");

                    b.ToTable("CLO", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("CLO_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.ConstructivistQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Question_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("QuestionDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_Detail");

                    b.Property<string>("QuestionName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_Name");

                    b.Property<int>("SessionNo")
                        .HasColumnType("int")
                        .HasColumnName("Session_No");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("QuestionId")
                        .HasName("PK__Construc__B0B2E4C62AEA54F9");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Constructivist_Question", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Constructivist_Question_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contract_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Contract_Date");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Contract_Value");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Contractor_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ContractId");

                    b.HasIndex("ContractorId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("LMCM_BE.Models.Curriculum", b =>
                {
                    b.Property<Guid>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Curriculum_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Approved_Date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Code");

                    b.Property<string>("CurriculumDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Description");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Name");

                    b.Property<string>("CurriculumNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curriculum_Name_English");

                    b.Property<string>("DecisionNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Decision_No");

                    b.Property<string>("EnglishVocationalName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("English_Vocational_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("VocationalCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Vocational_Code");

                    b.Property<string>("VocationalName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Vocational_Name");

                    b.HasKey("CurriculumId")
                        .HasName("PK__Curricul__2F88E2C21CA8612E");

                    b.ToTable("Curriculums");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Curriculums_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.CurriculumsSubject", b =>
                {
                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Curriculum_ID");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int>("Options")
                        .HasColumnType("int");

                    b.Property<int>("TermNo")
                        .HasColumnType("int")
                        .HasColumnName("Term_No");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CurriculumId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Curriculums_Subjects", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Curriculums_Subjects_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.DocumentTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Template_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Author_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Template_Name");

                    b.Property<string>("TemplateType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Template_Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TemplateId")
                        .HasName("PK__Document__E7FB8F012F99C312");

                    b.HasIndex("AuthorId");

                    b.ToTable("Document_Templates", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.GradingStructure", b =>
                {
                    b.Property<Guid>("StructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Structure_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AssessmentComponent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Assessment_Component");

                    b.Property<string>("AssessmentType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Assessment_Type");

                    b.Property<string>("Clo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("How")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Min_Value");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Part")
                        .HasColumnType("int");

                    b.Property<string>("QuestionNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_No");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Question_Type");

                    b.Property<string>("Reference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Scope")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SessionNo")
                        .HasColumnType("int")
                        .HasColumnName("Session_No");

                    b.Property<int>("StructureNo")
                        .HasColumnType("int")
                        .HasColumnName("Structure_No");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(19, 2)");

                    b.HasKey("StructureId")
                        .HasName("PK__Grading___71D721C6B560AAF0");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Grading_Structure", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Grading_Structure_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.LearningMaterial", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Material_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Edition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ISBN");

                    b.Property<string>("MaterialDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Material_Description");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Material_Name");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Published_Date");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Learning__3A09B0FD884B7FA8");

                    b.ToTable("Learning_Materials", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("LearningMaterials_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Notification_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User_ID");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Item_ID");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("LMCM_BE.Models.Plo", b =>
                {
                    b.Property<Guid>("PloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PLO_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Curriculum_ID");

                    b.Property<string>("PloDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PLO_Description");

                    b.Property<string>("PloName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PLO_Name");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PloId")
                        .HasName("PK__PLO__3BEF007EC7EFD1E5");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SubjectId");

                    b.ToTable("PLO", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PLO_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Schedule_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Clo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Itu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ITU");

                    b.Property<string>("LecturerMaterial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Lecturer_Material");

                    b.Property<string>("LecturerMaterialUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Lecturer_Material_Url");

                    b.Property<string>("LecturerTask")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Lecturer_Task");

                    b.Property<string>("Method")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ScheduleNo")
                        .HasColumnType("int")
                        .HasColumnName("Schedule_No");

                    b.Property<string>("StudentMaterial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Student_Material");

                    b.Property<string>("StudentMaterialUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Student_Material_Url");

                    b.Property<string>("StudentTask")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Student_Task");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__8C4D3BBB0610810D");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Schedule", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Schedule_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool?>("IsConstructivist")
                        .HasColumnType("bit")
                        .HasColumnName("isConstructivist");

                    b.Property<string>("Method")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Reality")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject_Code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject_Name");

                    b.Property<string>("SubjectNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject_Name_English");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("SubjectId");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ__Subjects__4A7C5769EA153DC8")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Subjects_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.SubjectsSyllabus", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Subject_ID");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("SubjectId", "SyllabusId");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Subjects_Syllabus", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Subjects_Syllabus_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.Syllabus", b =>
                {
                    b.Property<Guid>("SyllabusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Approved_Date");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Name");

                    b.Property<string>("CourseNameEnglish")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Course_Name_English");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DecisionNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Decision_No");

                    b.Property<string>("DegreeLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Degree_Level");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LearningTeachingMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Learning_Teaching_Method");

                    b.Property<decimal?>("MinGpaToPass")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Min_GPA_to_Pass");

                    b.Property<int>("NoOfCredits")
                        .HasColumnType("int")
                        .HasColumnName("No_of_Credits");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreRequisite")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pre_requisite");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Program_Name");

                    b.Property<decimal?>("ScoringScale")
                        .HasColumnType("decimal(19, 2)")
                        .HasColumnName("Scoring_Scale");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentTask")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Student_Task");

                    b.Property<string>("TimeAllocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Time_Allocation");

                    b.Property<string>("Tools")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("SyllabusId");

                    b.HasIndex(new[] { "CourseCode" }, "UQ__Syllabus__1AE5B24D9C85777D")
                        .IsUnique();

                    b.ToTable("Syllabus", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Syllabus_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.SyllabusLearningMaterial", b =>
                {
                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Syllabus_ID");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Material_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("SyllabusId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Syllabus_Learning_Materials", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Syllabus_Learning_Materials_History", "dbo");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("UpdatedAt")
                                    .HasColumnName("UpdatedAt");
                            }));
                });

            modelBuilder.Entity("LMCM_BE.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMCM_BE.Models.AcceptanceRecord", b =>
                {
                    b.HasOne("LMCM_BE.Models.Contract", "Contract")
                        .WithMany("AcceptanceRecords")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Acceptanc__Contr__04E4BC85");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("LMCM_BE.Models.BudgetProposal", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Author")
                        .WithMany("BudgetProposals")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Budget_Pr__Autho__7F2BE32F");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LMCM_BE.Models.Clo", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("Clos")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__CLO__Syllabus_ID__0F624AF8");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.ConstructivistQuestion", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("ConstructivistQuestions")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Construct__Sylla__08B54D69");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.Contract", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Contractor")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Contr__797309D9");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("LMCM_BE.Models.CurriculumsSubject", b =>
                {
                    b.HasOne("LMCM_BE.Models.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Curriculu__Curri__534D60F1");

                    b.HasOne("LMCM_BE.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Curriculu__Subje__5441852A");

                    b.Navigation("Curriculum");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LMCM_BE.Models.DocumentTemplate", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "Author")
                        .WithMany("DocumentTemplates")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Document___Updat__0A9D95DB");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LMCM_BE.Models.GradingStructure", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("GradingStructures")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Grading_S__Sylla__02084FDA");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.Notification", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__User___73BA3083");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMCM_BE.Models.Plo", b =>
                {
                    b.HasOne("LMCM_BE.Models.Curriculum", "Curriculum")
                        .WithMany("Plos")
                        .HasForeignKey("CurriculumId")
                        .IsRequired()
                        .HasConstraintName("FK__PLO__Curriculum___59FA5E80");

                    b.HasOne("LMCM_BE.Models.Subject", "Subject")
                        .WithMany("Plos")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__PLO__Subject_ID__5AEE82B9");

                    b.Navigation("Curriculum");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LMCM_BE.Models.Schedule", b =>
                {
                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany("Schedules")
                        .HasForeignKey("SyllabusId")
                        .IsRequired()
                        .HasConstraintName("FK__Schedule__Syllab__7B5B524B");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.SubjectsSyllabus", b =>
                {
                    b.HasOne("LMCM_BE.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Subjects___Subje__60A75C0F");

                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany()
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Subjects___Sylla__619B8048");

                    b.Navigation("Subject");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("LMCM_BE.Models.SyllabusLearningMaterial", b =>
                {
                    b.HasOne("LMCM_BE.Models.LearningMaterial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Syllabus___Mater__6E01572D");

                    b.HasOne("LMCM_BE.Models.Syllabus", "Syllabus")
                        .WithMany()
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Syllabus___Sylla__6D0D32F4");

                    b.Navigation("Material");

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LMCM_BE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMCM_BE.Models.Contract", b =>
                {
                    b.Navigation("AcceptanceRecords");
                });

            modelBuilder.Entity("LMCM_BE.Models.Curriculum", b =>
                {
                    b.Navigation("Plos");
                });

            modelBuilder.Entity("LMCM_BE.Models.Subject", b =>
                {
                    b.Navigation("Plos");
                });

            modelBuilder.Entity("LMCM_BE.Models.Syllabus", b =>
                {
                    b.Navigation("Clos");

                    b.Navigation("ConstructivistQuestions");

                    b.Navigation("GradingStructures");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("LMCM_BE.Models.User", b =>
                {
                    b.Navigation("BudgetProposals");

                    b.Navigation("Contracts");

                    b.Navigation("DocumentTemplates");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
