export enum MaterialTypeConstant {
  Online = "Oneline",
  Offline = "Offline",
}

export enum MaterialCategory {
  PublishedBook = 'Sách xuất bản chính thức',
  InternalBook = 'Sách xuất bản nội bộ',
  LicensedEbook = 'e-book có bản quyền',
  OpenSourceBook = 'Sách nguồn mở',
  OnlineResource = 'Tài nguyên trên mạng (website, youtube, ...)',
  UdemyCourse = 'Khóa học Udemy'
}

export enum Publisher {
  BachKhoaHaNoi = 'Bách khoa Hà Nội',
  ChinhTriQuocGiaSuThat = 'Chính trị Quốc gia Sự thật',
  CongThuong = 'Công Thương',
  CongAnNhanDan = 'Công an nhân dân',
  DanTri = 'Dân trí',
  GiaoThongVanTai = 'Giao thông vận tải',
  GiaoDucVietNam = 'Giáo dục Việt Nam',
  HangHai = 'Hàng hải',
  HocVienNongNghiep = 'Học viện Nông nghiệp',
  HongDuc = 'Hồng Đức',
  HoiNhaVan = 'Hội Nhà văn',
  KhoaHocTuNhienCongNghe = 'Khoa học Tự nhiên và Công nghệ',
  KhoaHocVaKyThuat = 'Khoa học và Kỹ thuật',
  KhoaHocXaHoi = 'Khoa học xã hội',
  KimDong = 'Kim Đồng',
  KinhTeTPHCM = 'Kinh tế thành phố Hồ Chí Minh',
  LaoDong = 'Lao động',
  LaoDongXaHoi = 'Lao động - Xã hội',
  LyLuanChinhTri = 'Lý luận Chính trị',
  MyThuat = 'Mỹ thuật',
  NongNghiep = 'Nông nghiệp',
  PhuNuVietNam = 'Phụ nữ Việt Nam',
  QuanDoiNhanDan = 'Quân đội nhân dân',
  SanKhau = 'Sân khấu',
  ThanhNien = 'Thanh niên',
  ThongTinTruyenThong = 'Thông tin và Truyền thông',
  ThongTan = 'Thông tấn',
  TheGioi = 'Thế giới',
  TheThaoVaDuLich = 'Thể thao và Du lịch',
  ThongKe = 'Thống kê',
  TriThuc = 'Tri thức',
  TaiChinh = 'Tài chính',
  TaiNguyenMoiTruongBanDo = 'Tài nguyên - Môi trường và Bản đồ Việt Nam',
  TonGiao = 'Tôn giáo',
  TuPhap = 'Tư Pháp',
  VanHoaThongTin = 'Văn hóa - thông tin',
  VanHoaDanToc = 'Văn hóa dân tộc',
  VanHoc = 'Văn học',
  XayDung = 'Xây dựng',
  YHoc = 'Y học',
  AmNhac = 'Âm nhạc',
  DHCongNghiepTPHCM = 'Đại học Công Nghiệp Thành phố Hồ Chí Minh',
  DHCaMau = 'Đại học Cần Thơ',
  DHHue = 'Đại học Huế',
  DHKinhTeQuocDan = 'Đại học Kinh tế Quốc dân',
  DHQuocGiaHaNoi = 'Đại học Quốc gia Hà Nội',
  DHQuocGiaTPHCM = 'Đại học Quốc gia Thành phố Hồ Chí Minh',
  DHSuPham = 'Đại học Sư phạm',
  DHThaiNguyen = 'Đại học Thái Nguyên',
  DHVinh = 'Đại học Vinh',
  DHSuPhamTPHCM = 'Đại học Sư phạm Thành phố Hồ Chí Minh',
  HaNoi = 'Hà Nội',
  HaiPhong = 'Hải Phòng',
  NgheAn = 'Nghệ An',
  PhuongDong = 'Phương Đông',
  ThanhHoa = 'Thanh Hóa',
  ThuanHoa = 'Thuận Hóa',
  Tre = 'Trẻ',
  TongHopTPHCM = 'Tổng hợp Thành phố Hồ Chí Minh',
  VanHoaVanNgheTPHCM = 'Văn hóa - Văn nghệ Thành phố Hồ Chí Minh',
  DaNang = 'Đà Nẵng',
  DongNai = 'Đồng Nai'
}